services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # prevent referencing to host
      - .:/app # . from host to /app in container
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules # prevent referencing to host
      - .:/app # . from host to /app in container
    command: ["npm", "run", "test"]